apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-development-tenant
  namespace: threescale-development
spec:
  email: dev@example.openshift.com
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale-gitops
  organizationName: development
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: 3scale-gitops
  systemMasterUrl: 'https://master.apps.rosa-nfvcf.ybvx.p1.openshiftapps.com'
  tenantSecretRef:
    name: tenant-secret
  username: admin