apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  name: threescale-prod
spec:
  destination:
    namespace: threescale-production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3scale/library-books-api/overlays/prod
    repoURL: https://github.com/col1985/3scale-gitops-overlay-custom.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true