apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale
  namespace: openshift-operators
spec:
  channel: threescale-2.15
  installPlanApproval: Automatic
  name: 3scale-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: 3scale-operator.v0.12.0